name: My Github Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v4
      - name: Chekouting the repository
      - run: printenv
      - run : echo "🍏 This job's name is ${{ github.job }}."
      - run : echo "🍏 This is env$ {{{ env.PROJECT_NAME }}}"
      # - run : echo "🍏 This job's name is ${{ github.job }}."